version: '3.7'

services:
  backend:
    build: 
      dockerfile: scripts/app/Dockerfile
      context: .
    environment:
      DB_HOST: postgres
    links:
      - postgres
    volumes:
      - ./src:/src
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s
